### PR TITLE
add electron to dependencies

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by etpinard** [comment]
Why?

**Comment by cpsievert** [comment]
```shell
$ plotly-graph-exporter '{"data":[{"y": [3, 2, 5, 3]}],"layout":{}}'

module.js:471
    throw err;
    ^

Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cpsievert/.nvm/versions/node/v6.9.5/lib/node_modules/image-exporter/bin/spawn-electron.js:3:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by etpinard** [comment]
So I guess you just cloned this repo and ran npm install?

One of the goals for this repo is to make standalone apps that don't require git, node, npm nor electron. I think for repos of the likes, it is customary to list electron as only a dev dep. I might be wrong here. We should double check. 

We could also publish an npm package for node users. But, that's far from the main user pool we're targeting.

**Comment by etpinard** [comment]
More in #21

**Comment by cpsievert** [comment]
Alright, I'm OK with closing this as long as the dependencies section in the readme properly explains what additional dependencies you might need to get the CLI working.

**Comment by etpinard** [comment]
> Alright, I'm OK with closing this as long as the dependencies section in the readme properly explains what additional dependencies you might need to get the CLI working.

Will be done in https://github.com/plotly/image-exporter/pull/74

**Pull request closed without merging**
