### PR TITLE
Bump vulnerable dev deps (take 2)

### PR DESCRIPTION
**Pull request by etpinard**
Supesedes https://github.com/plotly/image-exporter/pull/69 after I figured out the best way to _clear_ the CI `node_modules` cache (see https://github.com/plotly/image-exporter/pull/69 if that ever happens to you).

### CODE REVIEW

**Comment by etpinard** [comment]
merging this in.

**Comment by etpinard** [comment]
Looks like this worked. That

image


warning is gone.

**Comment by n-riesco** [comment]
So... the failure was just a cache corruption (because of the mismatch between `package.json` and `package-json.json`)?

**Comment by etpinard** [comment]
Ah I don't think so. Where does CircleCi that into account the `package.json`?

**Comment by JamesCropcho** [comment]
@etpinard @n-riesco 

> @JamesCropcho have you ever ran into issues like this one?

No (thankfully!).

> @etpinard I suspect the issue is that we are using the same keys to save caches for Node v6 and v8.

I too believe there's a high probability. Regardless, best-case scenario would be that this is a bad practice that would eventually cause some problem.

> Where does CircleCi take into account the package.json?

Off the top of my head, via `npm install` and, though a degree of separation (derivation)  `checksum "package-lock.json"`.

**Pull request merged**
